### ISSUE TITLE
Premiumize.me connection error, check settings

### ISSUE THREAD

**Issue by jamesah2008** [piejanssens/premiumizer#210]
I've checked my username and password 100 times. The Customer ID and API key should be what I am using?

> `
>  
> Log:
> 07-26 20:04:04: INFO : *************************************************************************************
> 07-26 20:04:04: INFO : ----------------Premiumizer.log file has been deleted as a precaution----------------
> 07-26 20:04:04: INFO : *************************************************************************************
> 07-26 20:04:04: INFO : *************************************************************************************
> 07-26 20:04:04: INFO : ---------------------------Premiumizer has been updated!!----------------------------
> 07-26 20:04:04: INFO : *************************************************************************************
> 07-26 20:04:04: INFO : Starting server on 0.0.0.0:5000 
> 07-26 20:04:04: ERROR : Uncaught exception
> Traceback (most recent call last):
>   File "./premiumizer/premiumizer.py", line 2397, in <module>
>     scheduler = APScheduler(GeventScheduler())
>   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
>     self.configure(gconfig, **options)
>   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 126, in configure
>     self._configure(config)
>   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 697, in _configure
>     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
>   File "/usr/local/lib/python3.7/site-packages/tzlocal/unix.py", line 131, in get_localzone
>     _cache_tz = _get_localzone()
>   File "/usr/local/lib/python3.7/site-packages/tzlocal/unix.py", line 125, in _get_localzone
>     raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
> pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
> 07-26 20:04:39: INFO : Starting server on 0.0.0.0:5000 
> 07-26 20:04:39: ERROR : Uncaught exception
> Traceback (most recent call last):
>   File "./premiumizer/premiumizer.py", line 2397, in <module>
>     scheduler = APScheduler(GeventScheduler())
>   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
>     self.configure(gconfig, **options)
>   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 126, in configure
>     self._configure(config)
>   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 697, in _configure
>     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
>   File "/usr/local/lib/python3.7/site-packages/tzlocal/unix.py", line 131, in get_localzone
>     _cache_tz = _get_localzone()
>   File "/usr/local/lib/python3.7/site-packages/tzlocal/unix.py", line 125, in _get_localzone
>     raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
> pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
> 07-26 20:05:12: INFO : Starting server on 0.0.0.0:5000 
> 07-26 20:05:12: ERROR : Uncaught exception
> Traceback (most recent call last):
>   File "./premiumizer/premiumizer.py", line 2397, in <module>
>     scheduler = APScheduler(GeventScheduler())
>   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
>     self.configure(gconfig, **options)
>   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 126, in configure
>     self._configure(config)
>   File "/usr/local/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 697, in _configure
>     self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
>   File "/usr/local/lib/python3.7/site-packages/tzlocal/unix.py", line 131, in get_localzone
>     _cache_tz = _get_localzone()
>   File "/usr/local/lib/python3.7/site-packages/tzlocal/unix.py", line 125, in _get_localzone
>     raise pytz.UnknownTimeZoneError('Can not find any timezone configuration')
> pytz.exceptions.UnknownTimeZoneError: 'Can not find any timezone configuration'
> 07-26 16:05:36: INFO : Starting server on 0.0.0.0:5000 
> 07-26 16:07:03: ERROR : premiumize.me error:  
> 07-26 16:07:54: INFO : Starting server on 0.0.0.0:5000 
> 07-26 16:09:21: ERROR : premiumize.me error:  
> 07-26 16:09:31: INFO : Settings saved, reloading configuration
> 07-26 16:09:54: INFO : Restarting
> 07-26 16:10:41: INFO : Starting server on 0.0.0.0:5000 
> 07-26 16:12:08: ERROR : premiumize.me error:  
> 07-26 16:13:48: ERROR : premiumize.me error:  
> 07-26 16:13:53: ERROR : premiumize.me error:  
> 07-26 16:15:11: ERROR : premiumize.me error:  
> 07-26 16:16:57: ERROR : premiumize.me error:  
> 07-26 16:18:24: ERROR : premiumize.me error:  
> 07-26 16:19:22: INFO : Starting server on 0.0.0.0:5000 
> 07-26 16:20:48: ERROR : premiumize.me error:  
> 07-26 16:21:11: INFO : Settings saved, reloading configuration
> 07-26 16:21:11: INFO : Creating Download Path at: tv
> 07-26 16:21:11: INFO : Creating Download Path at: movie
> 07-26 16:21:14: INFO : Restarting
> 07-26 16:22:39: INFO : Starting server on 0.0.0.0:5000 
> 07-26 16:24:05: ERROR : premiumize.me error:  
> 07-26 16:25:08: INFO : Settings saved, reloading configuration
> 07-26 16:25:10: INFO : Restarting
> DEBUG Log:
> 07-26 16:25:14       root                                     : DEBUG    : DEBUG Logfile Initialized
> 07-26 16:25:14       root                                     : DEBUG    : Initializing config
> 07-26 16:25:14       root                                     : DEBUG    : Initializing config complete
> 07-26 16:25:14       root                                     : DEBUG    : Initializing Flask
> 07-26 16:25:14       engineio.server                          : INFO     : Server initialized for gevent.
> 07-26 16:25:14       root                                     : DEBUG    : Initializing Flask complete
> 07-26 16:25:14       root                                     : DEBUG    : Initializing Database
> 07-26 16:25:14       root                                     : DEBUG    : Database cleared
> 07-26 16:25:14       root                                     : DEBUG    : Initializing Database complete
> 07-26 16:25:14       root                                     : INFO     : Starting server on 0.0.0.0:5000 
> 07-26 16:25:14       root                                     : DEBUG    : def load_tasks started
> 07-26 16:25:14       apscheduler.scheduler                    : INFO     : Scheduler started
> 07-26 16:25:14       apscheduler.scheduler                    : INFO     : Added job "update" to job store "default"
> 07-26 16:25:14       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
> 07-26 16:25:14       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-26 16:25:24.721687-04:00 (in 9.985308 seconds)
> 07-26 16:25:24       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
> 07-26 16:25:24       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-26 16:25:34.721687-04:00 (in 9.988696 seconds)
> 07-26 16:25:24       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:10], next run at: 2019-07-26 16:25:34 EDT)" (scheduled at 2019-07-26 16:25:24.721687-04:00)
> 07-26 16:25:24       root                                     : DEBUG    : def update started
> 07-26 16:25:24       root                                     : DEBUG    : def prem_connection started
> 07-26 16:25:24       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (1): www.premiumize.me:443
> 07-26 16:25:32       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
> 07-26 16:25:32       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
> 07-26 16:25:32       geventwebsocket.handler                  : INFO     : 172.17.0.1 - - [2019-07-26 16:25:32] "GET / HTTP/1.1" 200 2267 0.057642
> 07-26 16:25:32       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
> 07-26 16:25:32       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
> 07-26 16:25:32       engineio.server                          : INFO     : 88f27ce8c59e423387c46503c77a40a0: Sending packet OPEN data {'sid': '88f27ce8c59e423387c46503c77a40a0', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
> 07-26 16:25:32       root                                     : DEBUG    : Client connected
> 07-26 16:25:32       socketio.server                          : INFO     : emitting event "download_categories" to 88f27ce8c59e423387c46503c77a40a0 [/]
> 07-26 16:25:32       engineio.server                          : INFO     : 88f27ce8c59e423387c46503c77a40a0: Sending packet MESSAGE data 2["download_categories",{"data":["tv","movie"]}]
> 07-26 16:25:32       engineio.server                          : INFO     : 88f27ce8c59e423387c46503c77a40a0: Sending packet MESSAGE data 0
> 07-26 16:25:32       geventwebsocket.handler                  : INFO     : 172.17.0.1 - - [2019-07-26 16:25:32] "GET /socket.io/?EIO=3&transport=polling&t=MmlzSWX HTTP/1.1" 200 410 0.005569
> 07-26 16:25:32       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
> 07-26 16:25:32       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-26 16:25:33.460601-04:00 (in 0.997573 seconds)
> 07-26 16:25:32       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
> 07-26 16:25:32       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
> 07-26 16:25:32       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
> 07-26 16:25:32       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
> 07-26 16:25:32       geventwebsocket.handler                  : DEBUG    : Attempting to upgrade connection
> 07-26 16:25:32       geventwebsocket.handler                  : DEBUG    : WebSocket request accepted, switching protocols
> 07-26 16:25:32       engineio.server                          : INFO     : 88f27ce8c59e423387c46503c77a40a0: Received request to upgrade to websocket
> 07-26 16:25:32       geventwebsocket.handler                  : INFO     : 172.17.0.1 - - [2019-07-26 16:25:32] "GET /socket.io/?EIO=3&transport=polling&t=MmlzSXP&sid=88f27ce8c59e423387c46503c77a40a0 HTTP/1.1" 200 191 0.025946
> 07-26 16:25:32       engineio.server                          : INFO     : 88f27ce8c59e423387c46503c77a40a0: Upgrade to websocket successful
> 07-26 16:25:32       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (2): www.premiumize.me:443
> 07-26 16:25:37       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
> 07-26 16:25:37       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request`

**Comment by neox387** [comment]
It worked before update or new install?

Id and api key yes

I see first error 
File "/usr/local/lib/python3.7/site-packages/tzlocal/unix.py", line 125, in _get_localzone
raise pytz.UnknownTimeZoneError('Can not find any timezone configuration'

Tzlocal recently got bumped maybe it has problems mm..

**Comment by neox387** [comment]
made some changes for next PR only API Key is needed anymore

**Comment by jamesah2008** [comment]
It hasn’t worked at all for me. The TZ was a mistake on setup that has been fixed in the docker environmental variables but still seems to be doing nothing. I don’t think the container would start without it. But I can’t seem to know if it’s connecting to the API.

Thanks,

James

**Comment by neox387** [comment]
This new tzlocal should have fixes for docker to it seems:
- When no time zone configuration can be find, tzlocal now return UTC.
  This is a major difference from 1.x, where an exception would be raised.
  This change is because Docker images often have no configuration at all,
  and the unix utilities will then default to UTC, so we follow that.

**Comment by neox387** [comment]
Well api should work. only thing you can try is renew api key and put it in again ..

But first error is still that tzlocal it might fuck everything up..

**Comment by neox387** [comment]
but just to be clear with either of the 2 latest builds its not working for you ? then it's not the bump with tzlocal at least.. =D must be some docker config problem somewhere, guess you already had a look trough #88?  @piejanssens 

Success | latest | de4d270 | a day ago | a day ago
-- | -- | -- | -- | --
Success | latest | 3255444 | 2 days ago | 2 days ago

**Comment by jamesah2008** [comment]
I think I've tried the latest docker container on my synology but can't verify what's happening. It would be nice to know which version is running and have it published on my homepage.

![image](https://user-images.githubusercontent.com/8015816/61983453-6a1e3880-afce-11e9-9e8f-a2c6a491bdd2.png)
![image](https://user-images.githubusercontent.com/8015816/61983472-773b2780-afce-11e9-985e-d6ff436393ae.png)

**Comment by jamesah2008** [comment]
[premiumizerDEBUG (1).log](https://github.com/piejanssens/premiumizer/files/3437503/premiumizerDEBUG.1.log)

**Comment by neox387** [comment]
Looking at the debug log, it seems the connection does not do anything so I'm guessing firewall dropping it or something...

**Comment by neox387** [comment]
And ye need to find some way to display version number in Docker  .. #170 

Outside of Docker it says what commit is running on the settings page along with update info xP

**Comment by jbwolf82** [comment]
DEBUG Log:
07-27 19:03:59       root                                     : INFO     : Logfile Cleared
07-27 19:03:59       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:03:59] "POST /log HTTP/1.1" 200 1623 0.029000
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       urllib3.connectionpool                   : DEBUG    : Starting new HTTP connection (1): 127.0.0.1:49369
07-27 19:04:01       urllib3.connectionpool                   : DEBUG    : http://127.0.0.1:49369 "POST /t_3f721a8059b846f37f62ff8c9009592b672e9b5b_ea3f935acd9ad4f5741164ae01fc23dd/toolbar/getStatus HTTP/1.1" 200 None
07-27 19:04:01       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:04:01] "GET / HTTP/1.1" 200 2378 0.023001
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet OPEN data {'sid': '910f107dc1c24a6b811591bb86a0db92', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
07-27 19:04:01       root                                     : DEBUG    : Client connected
07-27 19:04:01       socketio.server                          : INFO     : emitting event "download_categories" to 910f107dc1c24a6b811591bb86a0db92 [/]
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet MESSAGE data 2["download_categories",{"data":["TV","Movies"]}]
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet MESSAGE data 0
07-27 19:04:01       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:04:01] "GET /socket.io/?EIO=3&transport=polling&t=Mmrv2gG HTTP/1.1" 200 411 0.018001
07-27 19:04:01       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
07-27 19:04:01       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-27 19:04:02.317991-05:00 (in 0.996996 seconds)
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Attempting to upgrade connection
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : WebSocket request accepted, switching protocols
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Received request to upgrade to websocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:04:01] "GET /socket.io/?EIO=3&transport=polling&t=Mmrv2gq&sid=910f107dc1c24a6b811591bb86a0db92 HTTP/1.1" 200 191 0.003110
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Upgrade to websocket successful
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-27 19:04:03.317991-05:00 (in 0.994903 seconds)
07-27 19:04:02       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:01], next run at: 2019-07-27 19:04:03 CDT)" (scheduled at 2019-07-27 19:04:02.317991-05:00)
07-27 19:04:02       root                                     : DEBUG    : def update started
07-27 19:04:02       root                                     : DEBUG    : def prem_connection started
07-27 19:04:02       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/transfer/list HTTP/1.1" 200 None
07-27 19:04:02       root                                     : ERROR    : premiumize.me login error: {"status":"error","message":"Not logged in. Please log in first."}
07-27 19:04:02       socketio.server                          : INFO     : emitting event "premiumize_connect_error" to all [/]
07-27 19:04:02       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet MESSAGE data 2["premiumize_connect_error",{}]
07-27 19:04:02       apscheduler.executors.default            : INFO     : Job "update (trigger: interval[0:00:10], next run at: 2019-07-27 19:04:12 CDT)" executed successfully
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-27 19:04:12.487036-05:00 (in 9.997027 seconds)
07-27 19:04:04       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:04       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request

**Comment by jbwolf82** [comment]
DEBUG Log:
07-27 19:03:59       root                                     : INFO     : Logfile Cleared
07-27 19:03:59       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:03:59] "POST /log HTTP/1.1" 200 1623 0.029000
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       urllib3.connectionpool                   : DEBUG    : Starting new HTTP connection (1): 127.0.0.1:49369
07-27 19:04:01       urllib3.connectionpool                   : DEBUG    : http://127.0.0.1:49369 "POST /t_3f721a8059b846f37f62ff8c9009592b672e9b5b_ea3f935acd9ad4f5741164ae01fc23dd/toolbar/getStatus HTTP/1.1" 200 None
07-27 19:04:01       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:04:01] "GET / HTTP/1.1" 200 2378 0.023001
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet OPEN data {'sid': '910f107dc1c24a6b811591bb86a0db92', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
07-27 19:04:01       root                                     : DEBUG    : Client connected
07-27 19:04:01       socketio.server                          : INFO     : emitting event "download_categories" to 910f107dc1c24a6b811591bb86a0db92 [/]
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet MESSAGE data 2["download_categories",{"data":["TV","Movies"]}]
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet MESSAGE data 0
07-27 19:04:01       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:04:01] "GET /socket.io/?EIO=3&transport=polling&t=Mmrv2gG HTTP/1.1" 200 411 0.018001
07-27 19:04:01       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
07-27 19:04:01       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-27 19:04:02.317991-05:00 (in 0.996996 seconds)
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Attempting to upgrade connection
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : WebSocket request accepted, switching protocols
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Received request to upgrade to websocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:04:01] "GET /socket.io/?EIO=3&transport=polling&t=Mmrv2gq&sid=910f107dc1c24a6b811591bb86a0db92 HTTP/1.1" 200 191 0.003110
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Upgrade to websocket successful
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-27 19:04:03.317991-05:00 (in 0.994903 seconds)
07-27 19:04:02       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:01], next run at: 2019-07-27 19:04:03 CDT)" (scheduled at 2019-07-27 19:04:02.317991-05:00)
07-27 19:04:02       root                                     : DEBUG    : def update started
07-27 19:04:02       root                                     : DEBUG    : def prem_connection started
07-27 19:04:02       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/transfer/list HTTP/1.1" 200 None
07-27 19:04:02       root                                     : ERROR    : premiumize.me login error: {"status":"error","message":"Not logged in. Please log in first."}
07-27 19:04:02       socketio.server                          : INFO     : emitting event "premiumize_connect_error" to all [/]
07-27 19:04:02       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet MESSAGE data 2["premiumize_connect_error",{}]
07-27 19:04:02       apscheduler.executors.default            : INFO     : Job "update (trigger: interval[0:00:10], next run at: 2019-07-27 19:04:12 CDT)" executed successfully
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-27 19:04:12.487036-05:00 (in 9.997027 seconds)
07-27 19:04:04       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:04       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request

**Comment by jbwolf82** [comment]
DEBUG Log:
07-27 19:03:59       root                                     : INFO     : Logfile Cleared
07-27 19:03:59       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:03:59] "POST /log HTTP/1.1" 200 1623 0.029000
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       urllib3.connectionpool                   : DEBUG    : Starting new HTTP connection (1): 127.0.0.1:49369
07-27 19:04:01       urllib3.connectionpool                   : DEBUG    : http://127.0.0.1:49369 "POST /t_3f721a8059b846f37f62ff8c9009592b672e9b5b_ea3f935acd9ad4f5741164ae01fc23dd/toolbar/getStatus HTTP/1.1" 200 None
07-27 19:04:01       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:04:01] "GET / HTTP/1.1" 200 2378 0.023001
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet OPEN data {'sid': '910f107dc1c24a6b811591bb86a0db92', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
07-27 19:04:01       root                                     : DEBUG    : Client connected
07-27 19:04:01       socketio.server                          : INFO     : emitting event "download_categories" to 910f107dc1c24a6b811591bb86a0db92 [/]
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet MESSAGE data 2["download_categories",{"data":["TV","Movies"]}]
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet MESSAGE data 0
07-27 19:04:01       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:04:01] "GET /socket.io/?EIO=3&transport=polling&t=Mmrv2gG HTTP/1.1" 200 411 0.018001
07-27 19:04:01       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
07-27 19:04:01       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-27 19:04:02.317991-05:00 (in 0.996996 seconds)
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Attempting to upgrade connection
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : WebSocket request accepted, switching protocols
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Received request to upgrade to websocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
07-27 19:04:01       geventwebsocket.handler                  : INFO     : 127.0.0.1 - - [2019-07-27 19:04:01] "GET /socket.io/?EIO=3&transport=polling&t=Mmrv2gq&sid=910f107dc1c24a6b811591bb86a0db92 HTTP/1.1" 200 191 0.003110
07-27 19:04:01       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Upgrade to websocket successful
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-27 19:04:03.317991-05:00 (in 0.994903 seconds)
07-27 19:04:02       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:01], next run at: 2019-07-27 19:04:03 CDT)" (scheduled at 2019-07-27 19:04:02.317991-05:00)
07-27 19:04:02       root                                     : DEBUG    : def update started
07-27 19:04:02       root                                     : DEBUG    : def prem_connection started
07-27 19:04:02       urllib3.connectionpool                   : DEBUG    : https://www.premiumize.me:443 "POST /api/transfer/list HTTP/1.1" 200 None
07-27 19:04:02       root                                     : ERROR    : premiumize.me login error: {"status":"error","message":"Not logged in. Please log in first."}
07-27 19:04:02       socketio.server                          : INFO     : emitting event "premiumize_connect_error" to all [/]
07-27 19:04:02       engineio.server                          : INFO     : 910f107dc1c24a6b811591bb86a0db92: Sending packet MESSAGE data 2["premiumize_connect_error",{}]
07-27 19:04:02       apscheduler.executors.default            : INFO     : Job "update (trigger: interval[0:00:10], next run at: 2019-07-27 19:04:12 CDT)" executed successfully
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
07-27 19:04:02       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-07-27 19:04:12.487036-05:00 (in 9.997027 seconds)
07-27 19:04:04       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
07-27 19:04:04       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request

**Comment by jbwolf82** [comment]
Not sure why but mine  is working again.

**Comment by neox387** [comment]
premiumize.me login error: {"status":"error","message":"Not logged in. Please log in first."}

So ye that is working just pm.me not accepting api key.

Could also verify in conf/settings.cfg if api key is right.

But if it's working.. The better

**Comment by jamesah2008** [comment]
I still can't figure out what's going on. Nothing seems to download. Port forwarded the docker container and canyouseeme.org shows good.

>09-23 21:37:18       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (240): www.premiumize.me:443
09-23 21:37:23       root                                     : ERROR    : premiumize.me error:  
09-23 21:37:23       socketio.server                          : INFO     : emitting event "premiumize_connect_error" to all [/]
09-23 21:37:23       engineio.server                          : INFO     : a41b6c8eedf845ddaa7192738da4656d: Client is gone, closing socket
09-23 21:37:23       root                                     : DEBUG    : Client disconnected
09-23 21:37:23       engineio.server                          : INFO     : a41b6c8eedf845ddaa7192738da4656d: Client is gone, closing socket
09-23 21:37:23       apscheduler.executors.default            : INFO     : Job "update (trigger: interval[0:00:10], next run at: 2019-09-23 20:37:33 UTC)" executed successfully
09-23 21:37:23       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:23       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:33.643568+00:00 (in 9.998863 seconds)
09-23 21:37:26       engineio.server                          : INFO     : a41b6c8eedf845ddaa7192738da4656d: Received packet PING data None
09-23 21:37:26       engineio.server                          : INFO     : Receive error -- socket is closed
09-23 21:37:26       geventwebsocket.handler                  : DEBUG    : Closed WebSocket
09-23 21:37:26       geventwebsocket.handler                  : DEBUG    : Failed to write closing frame -> closing socket
09-23 21:37:26       geventwebsocket.handler                  : DEBUG    : Closed WebSocket
09-23 21:37:33       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:33       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:43.643568+00:00 (in 9.993708 seconds)
09-23 21:37:33       apscheduler.executors.default            : INFO     : Running job "update (trigger: interval[0:00:10], next run at: 2019-09-23 20:37:43 UTC)" (scheduled at 2019-09-23 20:37:33.643568+00:00)
09-23 21:37:33       root                                     : DEBUG    : def update started
09-23 21:37:33       root                                     : DEBUG    : def prem_connection started
09-23 21:37:33       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (241): www.premiumize.me:443
09-23 21:37:38       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
09-23 21:37:38       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
09-23 21:37:38       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet OPEN data {'sid': 'd8ddfa6762e8459fabd84143fab36702', 'upgrades': ['websocket'], 'pingTimeout': 60000, 'pingInterval': 25000}
09-23 21:37:38       root                                     : DEBUG    : Client connected
09-23 21:37:38       socketio.server                          : INFO     : emitting event "download_categories" to d8ddfa6762e8459fabd84143fab36702 [/]
09-23 21:37:38       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet MESSAGE data 2["download_categories",{"data":["tv","movie","default"]}]
09-23 21:37:38       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet MESSAGE data 0
09-23 21:37:38       geventwebsocket.handler                  : INFO     : 172.17.0.1 - - [2019-09-23 21:37:38] "GET /socket.io/?EIO=3&transport=polling&t=MrVs0ZP HTTP/1.1" 200 388 0.004889
09-23 21:37:38       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:38       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:39.664989+00:00 (in 0.997853 seconds)
09-23 21:37:38       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
09-23 21:37:38       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
09-23 21:37:38       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
09-23 21:37:38       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
09-23 21:37:38       geventwebsocket.handler                  : DEBUG    : Attempting to upgrade connection
09-23 21:37:38       geventwebsocket.handler                  : DEBUG    : WebSocket request accepted, switching protocols
09-23 21:37:38       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received request to upgrade to websocket
09-23 21:37:38       geventwebsocket.handler                  : INFO     : 172.17.0.1 - - [2019-09-23 21:37:38] "GET /socket.io/?EIO=3&transport=polling&t=MrVs13l&sid=d8ddfa6762e8459fabd84143fab36702 HTTP/1.1" 200 159 0.012466
09-23 21:37:38       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Upgrade to websocket successful
09-23 21:37:39       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:39       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:39 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:37:39       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:40.664989+00:00 (in 0.998275 seconds)
09-23 21:37:40       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:40       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:40 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:37:40       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:41.664989+00:00 (in 0.997227 seconds)
09-23 21:37:41       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (242): www.premiumize.me:443
09-23 21:37:46       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:46       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:41 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:37:46       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:47.664989+00:00 (in 0.995182 seconds)
09-23 21:37:47       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:47       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:47 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:37:47       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:48.664989+00:00 (in 0.998001 seconds)
09-23 21:37:48       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:48       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:48 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:37:48       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:49.664989+00:00 (in 0.998188 seconds)
09-23 21:37:49       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:49       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:49 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:37:49       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:50.664989+00:00 (in 0.997394 seconds)
09-23 21:37:49       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (243): www.premiumize.me:443
09-23 21:37:54       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:54       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:50 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:37:54       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:55.664989+00:00 (in 0.986013 seconds)
09-23 21:37:55       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:55       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:55 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:37:55       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:56.664989+00:00 (in 0.998285 seconds)
09-23 21:37:56       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:56       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:56 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:37:56       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:57.664989+00:00 (in 0.997570 seconds)
09-23 21:37:57       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:37:57       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:57 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:37:57       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:37:58.664989+00:00 (in 0.997864 seconds)
09-23 21:37:57       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (244): www.premiumize.me:443
09-23 21:38:02       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:02       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:37:58 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:02       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:03.664989+00:00 (in 0.978019 seconds)
09-23 21:38:03       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:03       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:03 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:03       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:04.664989+00:00 (in 0.997993 seconds)
09-23 21:38:04       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:04       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:04 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:04       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:05.664989+00:00 (in 0.998287 seconds)
09-23 21:38:05       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:05       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:05 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:05       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:06.664989+00:00 (in 0.997292 seconds)
09-23 21:38:05       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (245): www.premiumize.me:443
09-23 21:38:10       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:10       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:06 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:10       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:11.664989+00:00 (in 0.968959 seconds)
09-23 21:38:11       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:11       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:11 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:11       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:12.664989+00:00 (in 0.998172 seconds)
09-23 21:38:12       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:12       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:12 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:12       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:13.664989+00:00 (in 0.997393 seconds)
09-23 21:38:13       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:13       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:13 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:13       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:14.664989+00:00 (in 0.997326 seconds)
09-23 21:38:13       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:38:13       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:38:13       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (246): www.premiumize.me:443
09-23 21:38:18       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:18       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:14 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:18       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:19.664989+00:00 (in 0.959962 seconds)
09-23 21:38:19       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:19       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:19 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:19       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:20.664989+00:00 (in 0.997328 seconds)
09-23 21:38:20       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:20       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:20 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:20       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:21.664989+00:00 (in 0.997327 seconds)
09-23 21:38:21       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:21       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:21 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:21       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:22.664989+00:00 (in 0.997327 seconds)
09-23 21:38:21       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (247): www.premiumize.me:443
09-23 21:38:26       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:26       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:22 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:26       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:27.664989+00:00 (in 0.950735 seconds)
09-23 21:38:27       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:27       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:27 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:27       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:28.664989+00:00 (in 0.997929 seconds)
09-23 21:38:28       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:28       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:28 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:28       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:29.664989+00:00 (in 0.997843 seconds)
09-23 21:38:29       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:29       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:29 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:29       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:30.664989+00:00 (in 0.998047 seconds)
09-23 21:38:29       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (248): www.premiumize.me:443
09-23 21:38:34       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:34       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:30 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:34       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:35.664989+00:00 (in 0.940925 seconds)
09-23 21:38:35       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:35       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:35 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:35       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:36.664989+00:00 (in 0.998000 seconds)
09-23 21:38:36       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:36       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:36 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:36       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:37.664989+00:00 (in 0.998274 seconds)
09-23 21:38:37       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:37       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:37 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:37       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:38.664989+00:00 (in 0.997375 seconds)
09-23 21:38:37       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (249): www.premiumize.me:443
09-23 21:38:42       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:42       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:38 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:42       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:43.664989+00:00 (in 0.932792 seconds)
09-23 21:38:43       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:38:43       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:38:43       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:43       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:43 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:43       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:44.664989+00:00 (in 0.998139 seconds)
09-23 21:38:44       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:44       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:44 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:44       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:45.664989+00:00 (in 0.997394 seconds)
09-23 21:38:45       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:45       apscheduler.scheduler                    : WARNING  : Execution of job "update (trigger: interval[0:00:01], next run at: 2019-09-23 20:38:45 UTC)" skipped: maximum number of running instances reached (1)
09-23 21:38:45       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:38:46.664989+00:00 (in 0.997508 seconds)
09-23 21:38:45       urllib3.connectionpool                   : DEBUG    : Starting new HTTPS connection (250): www.premiumize.me:443
09-23 21:38:50       root                                     : ERROR    : premiumize.me error:  
09-23 21:38:50       socketio.server                          : INFO     : emitting event "premiumize_connect_error" to all [/]
09-23 21:38:50       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet MESSAGE data 2["premiumize_connect_error",{}]
09-23 21:38:50       apscheduler.executors.default            : INFO     : Job "update (trigger: interval[0:05:00], next run at: 2019-09-23 20:43:50 UTC)" executed successfully
09-23 21:38:50       apscheduler.scheduler                    : DEBUG    : Looking for jobs to run
09-23 21:38:50       apscheduler.scheduler                    : DEBUG    : Next wakeup is due at 2019-09-23 20:43:50.741650+00:00 (in 299.998477 seconds)
09-23 21:39:13       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:39:13       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:39:43       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:39:43       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:40:08       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:40:08       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:40:43       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:40:43       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:41:08       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:41:08       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:41:43       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:41:43       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:42:08       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:42:08       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:42:33       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:42:33       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:42:58       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Received packet PING data None
09-23 21:42:58       engineio.server                          : INFO     : d8ddfa6762e8459fabd84143fab36702: Sending packet PONG data None
09-23 21:42:59       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
09-23 21:42:59       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
09-23 21:42:59       geventwebsocket.handler                  : INFO     : 172.17.0.1 - - [2019-09-23 21:42:59] "GET /log HTTP/1.1" 200 6861 0.195840
09-23 21:42:59       geventwebsocket.handler                  : DEBUG    : Closed WebSocket
09-23 21:42:59       root                                     : DEBUG    : Client disconnected
09-23 21:43:01       geventwebsocket.handler                  : DEBUG    : Initializing WebSocket
09-23 21:43:01       geventwebsocket.handler                  : DEBUG    : Validating WebSocket request
09-23 21:43:01       geventwebsocket.handler                  : DEBUG    : Can only upgrade connection if using GET method.

>
